### ISSUE TITLE
Recomendación ortográfica

### ISSUE THREAD

**Issue by jhonjgr** [IreYuri/Trivia#1]
Corregir la palabra pondras por pondrás y la palabra Como por Cómo.
![image](https://user-images.githubusercontent.com/113283317/190929739-d3c0e674-9d09-4d62-b4f7-f79e41c5c187.png)
Travesía, Sabiduría y minúscula.
![image](https://user-images.githubusercontent.com/113283317/190929818-6d297038-99df-47de-88e5-f6583484098d.png)
Redoble
![image](https://user-images.githubusercontent.com/113283317/190929916-8baee1d1-e329-4fa1-8a71-70cca6b7c7c8.png)

**Comment by IreYuri** [comment]
Cierto, voy a cambiar eso de una vez.
Gracias por el dato! :)
