### ISSUE TITLE
Recomendación de diseño

### ISSUE THREAD

**Issue by jhonjgr** [IreYuri/Trivia#3]
Al momento de imprimir el puntaje después de las preguntas Como esta resaltado de Verde seria ideal poner las letras en blanco y no en negro para que se vea mejor.
![image](https://user-images.githubusercontent.com/113283317/190930126-960b7614-08e7-4983-951b-93e775f7fb08.png)

**Comment by IreYuri** [comment]
Tienes razón se ve mucho mejor con blanco. 
Gracias por la recomendación :)
